const deusas = [
  {
    id: 1,
    nome: "Aditi",
    origem: "Hindu",
    secao: "Criatividade",
    página: 14,
    palavraChave: "felicidade",
  },
  {
    id: 2,
    nome: "Eos",
    origem: "Grega e Romana",
    secao: "Poder",
    página: 65,
    palavraChave: "caminhos",
  },
  {
    id: 3,
    nome: "Afrodite",
    origem: "Grega e Romana",
    secao: "Amor",
    página: 36,
    palavraChave: "amor",
  },
  {
    id: 4,
    nome: "Lakshmi",
    origem: "Hindu",
    secao: "Poder",
    página: 68,
    palavraChave: "prosperidade",
  },
  {
    id: 5,
    nome: "Kali",
    origem: "Indiana",
    secao: "Proteger",
    página: 87,
    palavraChave: "proteção",
  },
  {
    id: 6,
    nome: "Ártemis",
    origem: "Grega e Romana",
    secao: "Poder",
    página: 60,
    palavraChave: "caça",
  },
  {
    id: 7,
    nome: "Hator",
    origem: "Egípcia",
    secao: "Amor",
    página: 42,
    palavraChave: "relacionamento",
  },
  {
    id: 8,
    nome: "Hina",
    origem: "Polinésia",
    secao: "Reinventar",
    página: 111,
    palavraChave: "mudança",
  },
  {
    id: 9,
    nome: "Freya",
    origem: "Escandinava",
    secao: "Amor",
    página: 41,
    palavraChave: "aventura",
  },
  {
    id: 10,
    nome: "Iemanjá",
    origem: "Iorubá",
    representação: "Proteger",
    página: 98,
    palavraChave: "pensamentos",
  },
  {
    id: 11,
    nome: "Amaterasu",
    origem: "Xintoísta",
    secao: "Poder",
    página: 59,
    palavraChave: "poder interior",
  },
  {
    id: 12,
    nome: "Chalchiuhtlicue",
    origem: "Asteca",
    secao: "Reinventar",
    página: 104,
    palavraChave: "recomeço",
  },
  {
    id: 13,
    nome: "Laka",
    origem: "Havaiana",
    secao: "Amor",
    página: 46,
    palavraChave: "riqueza",
  },
  {
    id: 14,
    nome: "Rhiannon",
    origem: "Galesa",
    secao: "Reinventar",
    página: 94,
    palavraChave: "proteção",
  },
  {
    id: 15,
    nome: "Tara",
    origem: "Hindu",
    secao: "Proteger",
    página: 96,
    palavraChave: "ajuda",
  },
  {
    id: 16,
    nome: "Mulher Aranha",
    origem: "Tribos nativas norte-americanas do Sudoeste",
    secao: "Criatividade",
    página: 31,
    palavraChave: "energia",
  },
  {
    id: 17,
    nome: "Ixchel",
    origem: "Maia",
    secao: "Reinventar",
    página: 115,
    palavraChave: "caminho",
  },
  {
    id: 18,
    nome: "Deméter",
    origem: "Grega Romana",
    secao: "Poder",
    página: 63,
    palavraChave: "cultivo",
  },
  {
    id: 19,
    nome: "Parvati",
    origem: "Hindu",
    secao: "Amor",
    página: 50,
    palavraChave: "persistência",
  },
  {
    id: 20,
    nome: "Mazu",
    origem: "Chinesa",
    secao: "Proteger",
    página: 93,
    palavraChave: "viagem",
  },
  {
    id: 21,
    nome: "Nüwa",
    origem: "Chinesa",
    secao: "Criatividade",
    página: 25,
    palavraChave: "criação",
  },
  {
    id: 22,
    nome: "Ala",
    origem: "Igbo",
    secao: "Proteger",
    página: 78,
    palavraChave: "justiça",
  },
  {
    id: 23,
    nome: "Hsi Wang Mu",
    origem: "Chinesa",
    secao: "Reinventar",
    página: 112,
    palavraChave: "renovação",
  },
  {
    id: 24,
    nome: "Ísis",
    origem: "Egípicia",
    secao: "Amor",
    página: 45,
    palavraChave: "esperança",
  },
  {
    id: 25,
    nome: "Pele",
    origem: "Havaiana",
    secao: "Poder",
    página: 74,
    palavraChave: "convicção",
  },
  {
    id: 26,
    nome: "As Musas",
    origem: "Grega",
    secao: "Criatividade",
    página: 22,
    palavraChave: "inspiração",
  },
  {
    id: 27,
    nome: "Cordélia",
    origem: "Galesa",
    secao: "Amor",
    página: 39,
    palavraChave: "amor-próprio",
  },
  {
    id: 28,
    nome: "Hécate",
    origem: "Grega Romana",
    secao: "Proteger",
    página: 84,
    palavraChave: "noite",
  },
  {
    id: 29,
    nome: "Psiquê",
    origem: "Grega",
    secao: "Amor",
    página: 52,
    palavraChave: "coração",
  },
  {
    id: 30,
    nome: "Brígida",
    origem: "Irlandesa",
    secao: "Proteger",
    página: 80,
    palavraChave: "paz",
  },
  {
    id: 31,
    nome: "Bast",
    origem: "Egípcia",
    secao: "Reinventar",
    página: 103,
    palavraChave: "cura",
  },
  {
    id: 32,
    nome: "Saraswati",
    origem: "Hindu",
    secao: "Criatividade",
    página: 28,
    palavraChave: "criatividade",
  },
  {
    id: 33,
    nome: "Gaia",
    origem: "Grega Romana",
    secao: "Poder",
    página: 66,
    palavraChave: "natureza",
  },
  {
    id: 34,
    nome: "Kuan Yin",
    origem: "Chinesa",
    secao: "Proteger",
    página: 88,
    palavraChave: "compaixão",
  },
  {
    id: 35,
    nome: "Áine",
    origem: "Celta",
    secao: "Poder",
    página: 56,
    palavraChave: "interior",
  },
  {
    id: 36,
    nome: "Ran",
    origem: "Nórdica",
    secao: "Criatividade",
    página: 26,
    palavraChave: "persistência",
  },
  {
    id: 37,
    nome: "Lieu Hanh",
    origem: "Vietnamita",
    secao: "Poder",
    página: 71,
    palavraChave: "feminina",
  },
  {
    id: 38,
    nome: "Xochiquetzal",
    origem: "Asteca",
    secao: "Reinventar",
    página: 120,
    palavraChave: "beleza",
  },
  {
    id: 39,
    nome: "Atena",
    origem: "Grega Romana",
    secao: "Criatividade",
    página: 17,
    palavraChave: "intuição",
  },
  {
    id: 40,
    nome: "Benten",
    origem: "Japonesa",
    secao: "Criatividade",
    página: 19,
    palavraChave: "sorte",
  },
  {
    id: 41,
    nome: "Chang-O",
    origem: "Chinesa",
    secao: "Criatividade",
    página: 21,
    palavraChave: "resposta",
  },
  {
    id: 42,
    nome: "Tiché",
    origem: "Grega Romana",
    secao: "Criatividade",
    página: 32,
    palavraChave: "fortuna",
  },
  {
    id: 43,
    nome: "Oxum",
    origem: "Iorubá",
    secao: "Amor",
    página: 49,
    palavraChave: "perdão",
  },
  {
    id: 44,
    nome: "Iansã",
    origem: "Iorubá",
    secao: "Proteger",
    página: 72,
    palavraChave: "verdade",
  },
  {
    id: 45,
    nome: "Durga",
    origem: "Hindu",
    secao: "Proteger",
    página: 83,
    palavraChave: "proteção",
  },
  {
    id: 46,
    nome: "Ma'at",
    origem: "Egípcia",
    secao: "Proteger",
    página: 91,
    palavraChave: "justiça",
  },
  {
    id: 47,
    nome: "Estsanatlehi",
    origem: "Nativo norte-americana",
    secao: "Reinventar",
    página: 107,
    palavraChave: "transformação",
  },
  {
    id: 48,
    nome: "Hel",
    origem: "Nórdica",
    secao: "Reinventar",
    página: 108,
    palavraChave: "recomeço",
  },
  {
    id: 49,
    nome: "Nyai Loro Kidul",
    origem: "Indonésia",
    secao: "Reinventar",
    página: 117,
    palavraChave: "transformação",
  },
  {
    id: 50,
    nome: "Sekhmet",
    origem: "Egípcia",
    secao: "Reinventar",
    página: 118,
    palavraChave: "cura",
  },
];

module.exports = deusas;
